---
- name: Run assertions
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - "../../common/tasks/assert_ubuntu.yaml"

- name: Include common handlers
  ansible.builtin.include_role:
    role: common_handlers

- name: Add .bashrc to the root's home directory
  ansible.builtin.copy:
    src: .bashrc_root
    dest: /root/.bashrc
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: &shell_tags
    - shell

- name: Add .bashrc to the ubuntu's home directory
  ansible.builtin.copy:
    src: .bashrc_user
    dest: /home/ubuntu/.bashrc
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
  become_user: ubuntu
  tags: *shell_tags

- name: Add aliases to the root's .shell_aliases_ansible file
  ansible.builtin.template:
    src: .shell_aliases_ansible.j2
    dest: /root/.shell_aliases_ansible
    owner: root
    group: root
    mode: '0644'
  vars:
    aliases: "{{ shell_aliases_default + shell_aliases_extra }}"
  become: true
  tags: *shell_tags

- name: Add aliases to the ubuntu's .shell_aliases_ansible file
  ansible.builtin.template:
    src: .shell_aliases_ansible.j2
    dest: /home/ubuntu/.shell_aliases_ansible
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  vars:
    aliases: "{{ shell_aliases_default + shell_aliases_extra }}"
  become: true
  become_user: ubuntu
  tags: *shell_tags

- name: Create backup of /etc/skel/.bashrc file
  ansible.builtin.copy:
    src: /etc/skel/.bashrc
    dest: /etc/skel/.bashrc.original
    owner: root
    group: root
    mode: '0644'
    remote_src: true
    backup: false
    force: false # Do not overwrite if the file already exists.
  become: true
  tags: *shell_tags

- name: Add the .bashrc file to the system skeleton directory
  ansible.builtin.copy:
    src: .bashrc_user
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: *shell_tags

- name: Add files to the update-motd.d directory
  ansible.builtin.copy:
    src: "update-motd.d/{{ item }}"
    dest: "/etc/update-motd.d/{{ item }}"
    owner: root
    group: root
    mode: '0750'
  loop:
    - 00-header
  become: true
  tags: &motd_tags
    <<*shell_tags
    - motd

- name: Delete any existing /etc/motd file
  ansible.builtin.file:
    path: /etc/motd
    state: absent
  become: true
  tags: *motd_tags

- name: Ensure tmux is installed
  ansible.builtin.package:
    name: tmux
    state: present
  become: true
  tags: &tmux_tags
    <<*shell_tags
    - tmux

- name: Add the tmux.conf file the system
  ansible.builtin.copy:
    src: tmux.conf
    dest: /etc/tmux.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: *tmux_tags

- name: Ensure nano and vim are installed
  ansible.builtin.package:
    name:
      - nano
      - vim
    state: present
  become: true
  tags:
    <<*shell_tags
    - nano
    - vim

- name: Add the .nanorc file to the root's home directory
  ansible.builtin.copy:
    src: .nanorc
    dest: /root/.nanorc
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: &nano_tags
    <<*shell_tags
    - nano

- name: Add the .nanorc file to the ubuntu's home directory
  ansible.builtin.copy:
    src: .nanorc
    dest: /home/ubuntu/.nanorc
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
  become_user: ubuntu
  tags: *nano_tags

- name: Add the .nanorc file to the system skeleton directory
  ansible.builtin.copy:
    src: .nanorc
    dest: /etc/skel/.nanorc
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: *nano_tags

- name: Add the .vimrc file to the root's home directory
  ansible.builtin.copy:
    src: .vimrc
    dest: /root/.vimrc
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: &vim_tags
    <<*shell_tags
    - vim

- name: Add the .vimrc file to the ubuntu's home directory
  ansible.builtin.copy:
    src: .vimrc
    dest: /home/ubuntu/.vimrc
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
  become_user: ubuntu
  tags: *vim_tags

- name: Add the .vimrc file to the system skeleton directory
  ansible.builtin.copy:
    src: .vimrc
    dest: /etc/skel/.vimrc
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: *vim_tags
