---
- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  become: true
  listen: restart_ssh

- name: Reboot the system
  ansible.builtin.reboot:
    connect_timeout: 5
    pre_reboot_delay: 0
    post_reboot_delay: 60
  become: true
  listen: reboot_system
