---
- name: Run assertions
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - "../../common/tasks/assert_ubuntu.yaml"

- name: Include common handlers
  ansible.builtin.include_role:
    role: common_handlers

- name: Ensure the SSH server is installed
  ansible.builtin.package:
    name: openssh-server
    state: present
  become: true
  tags: &ssh_tags
    - ssh

- name: Comment out configuration that accepts locale variables
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AcceptEnv\s+LANG\s+LC_.*'
    line: '#AcceptEnv LANG LC_*'
    state: present
  become: true
  notify: restart_ssh
  tags: *ssh_tags

- name: Ensure the SSH daemon configuration file is present
  ansible.builtin.template:
    src: ssh_config_ansible.conf.j2
    dest: /etc/ssh/sshd_config.d/sshd_config_ansible.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    file_list: "{{ ssh_extra_authorized_keys_files }}"
  become: true
  notify: restart_ssh
  tags: *ssh_tags

- name: Add authorized keys for the root user
  ansible.builtin.template:
    src: authorized_keys_ansible.j2
    dest: /root/.ssh/authorized_keys_ansible
    owner: root
    group: root
    mode: '0600'
  vars:
    authorized_keys: "{{ ssh_authorized_keys_root or ssh_authorized_keys_administrator }}"
  become: true
  tags: *ssh_tags

- name: Add authorized keys for the administrator user
  ansible.builtin.template:
    src: authorized_keys_ansible.j2
    dest: /home/ubuntu/.ssh/authorized_keys_ansible
    owner: ubuntu
    group: ubuntu
    mode: '0600'
  vars:
    authorized_keys: "{{ ssh_authorized_keys_administrator }}"
  become: true
  become_user: ubuntu
  tags: *ssh_tags
