name: ${PROJECT_NAME}

networks:
  internal:
    driver: bridge

services:
  database:
    image: 'postgres:17.6'
    hostname: 'database.internal'
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
      - POSTGRES_PASSWORD=${PG_ROOT_PASSWORD}
      - POSTGRES_DB=${TERRAHARBOR_DB_NAME}
      - TERRAHARBOR_DB_NAME=${TERRAHARBOR_DB_NAME}
      - TERRAHARBOR_DB_USER=${TERRAHARBOR_DB_USER}
      - TERRAHARBOR_DB_PASSWORD=${TERRAHARBOR_DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw # This path will change for versions >= 18. Check official documentation of the Docker image.
      - ../../backend/database/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh:ro
      - ../../backend/database/db-init-scripts:/db-init-scripts:ro
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 127.0.0.1 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      - TZ=Europe/Zurich
      - POSTGRES_HOST=database.internal
      - POSTGRES_DB=${TERRAHARBOR_DB_NAME}
      - POSTGRES_USER=${TERRAHARBOR_DB_USER}
      - POSTGRES_PASSWORD=${TERRAHARBOR_DB_PASSWORD}
    ports:
      - 8000:8000
    volumes:
      - tf-states:/data:rw
    networks:
      - internal

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      # TODO Add healthcheck for backend service
      # backend:
      #   condition: service_healthy
    environment:
      - TZ=Europe/Zurich
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=${FRONTEND_PORT}"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    networks:
      - internal

  reverseproxy:
    image: 'traefik:3.5.1'
    restart: unless-stopped
    # TODO Add healthcheck for frontend service
    # depends_on:
    #   frontend:
    #     condition: service_healthy
    environment:
      - TZ=Europe/Zurich
    command:
      - "--global.checknewversion=false"
      - "--global.sendAnonymousUsage=false"
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    networks:
      - internal
    ports:
      - 80:80
      - 8080:8080 # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  db-data:
  tf-states:
