---
- name: Run assertions
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - "../../common/tasks/assert_ubuntu.yaml"

- name: Include common handlers
  ansible.builtin.include_role:
    role: common_handlers

- name: Include locales task
  ansible.builtin.include_tasks: locales
