---
- name: Run assertions
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - "../../common/tasks/assert_ubuntu.yaml"

- name: Include common handlers
  ansible.builtin.include_role:
    role: common_handlers

- name: Create necessary directories
  ansible.builtin.file:
    path: /home/ubuntu/terraharbor
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Checkout `backend` repository
  ansible.builtin.git:
    repo: 'https://github.com/terraharbor/backend.git'
    dest: /tmp/backend
    version: "{{ docker_apply_repo_version_backend }}"
    force: yes

- name: Copy database initialization scripts
  ansible.builtin.copy:
    src: /tmp/backend/database
    dest: /home/ubuntu/terraharbor/
    remote_src: true # The files are on the destination host.
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    force: true

- name: Checkout `infrastructure` repository
  ansible.builtin.git:
    repo: 'https://github.com/terraharbor/infrastructure.git'
    dest: /tmp/infrastructure
    version: "{{ docker_apply_repo_version_infrastructure }}"
    force: yes

- name: Copy Docker Compose files
  ansible.builtin.copy:
    src: "/tmp/infrastructure/docker-compose/{{ item }}"
    dest: /home/ubuntu/terraharbor/
    remote_src: true # The files are on the destination host.
    owner: ubuntu
    group: ubuntu
    mode: '0644'
    force: true
  loop:
    - "docker-compose.yaml"
    - ".env"

- name: Create .env_ansible file
  ansible.builtin.template:
    src: ".env_ansible.j2"
    dest: /home/ubuntu/terraharbor/.env_ansible
    owner: ubuntu
    group: ubuntu
    mode: '0644'
    force: true

- name: Apply Docker Compose
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/terraharbor
    files:
      - docker-compose.yaml
    env_files:
      - .env
      - .env_ansible
