---
- name: Apply configuration to Debian VMs
  hosts: azure_vms
  vars:

  tasks:
    - name: Run ssh
      ansible.builtin.include_role:
        name: ssh
      tags:
        - ssh

    - name: Run locales from settings
      ansible.builtin.include_role:
        name: settings
        tasks_from: locales
      tags:
        - settings
        - locales

    - name: Run upgrade_packages from packages
      ansible.builtin.include_role:
        name: packages
        tasks_from: upgrade_packages
      tags:
        - packages
        - upgrade_packages

    - name: Run install_packages from packages
      ansible.builtin.include_role:
        name: packages
        tasks_from: install_packages
      tags:
        - packages
        - install_packages

    - name: Run shell
      ansible.builtin.include_role:
        name: shell
      tags:
        - shell
        - motd
        - tmux
        - vim
        - nano

    - name: Run docker
      ansible.builtin.include_role:
        name: docker
      tags:
        - docker
